- community.crypto.openssl_privatekey:
    path: "{{ input_leap_config_ssl_key_file_path }}"
    size: 4096
    type: RSA
    return_content: true
  register: input_leap_config_ssl_key_file_result
  no_log: true
