- import_role:
    name: kgit_workspace.local_branch_info.list_branches

- include_role:
    name: kgit_workspace.purge.soft_git_branch_delete_if_no_upstream_set
  loop: "{{ _detected_git_workspace_branch_name_list }}"
  loop_control:
    loop_var: _git_workspace_branch_name_to_delete
  vars:
    git_workspace_branch_name: "{{ _git_workspace_branch_name_to_delete }}"