- file:
    path: "{{ global_config_git_dir_path }}"
    state: directory

- lineinfile:
    path: "{{ global_config_git_ignore_file_path }}"
    line: "{{ global_config_git_ignore_file_entry }}"
    create: yes

- name: Set global git excludesFile to use custom ignore file
  community.general.git_config:
    name: core.excludesFile
    value: "{{ global_config_git_ignore_file_path }}"
    scope: global
