- name: Ensure EE {{ container_name }} is started from {{ container_image_full_path }}
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "{{ container_image_full_path }}"
    interactive: true
    network: host
    command: bash
    label:
      ansible-execution-environment: true
    workdir: /runner