- import_role:
    name: kgit_workspace.info.upstream_tracking_branches
- debug:
    var: _git_workspace_branches_upstream_data_mapsplit_mapzip_mapmapreverse_mapdict_with_upstream_defined_and_gone_just_branches
- include_role:
    name: upstream_tracking_branch_unset
  loop: "{{ _git_workspace_branches_upstream_data_mapsplit_mapzip_mapmapreverse_mapdict_with_upstream_defined_and_gone_just_branches }}"
  loop_control:
    loop_var: __git_workspace_branch_name
  vars:
    git_workspace_branch_name: "{{ __git_workspace_branch_name }}"