ssh_priv_key_file_path: "{{ ssh_keypair_directory_path }}/{{ ssh_priv_key_filename }}"
ssh_keypair_pub_key_filename: "{{ ssh_priv_key_filename }}.pub"
ssh_keypair_pub_key_file_path: "{{ ssh_keypair_directory_path }}/{{ ssh_keypair_pub_key_filename }}"
ssh_priv_key_file_path_relative_to_xdg_user_home: "{{ ssh_priv_key_file_path | ansible.builtin.relpath(xdg_user_home_path) }}"
ssh_priv_key_filename: id_rsa

_detected_openssh_keypair_public_key_value: "{{ _ssh_priv_key_result.public_key }}"
_detected_openssh_keypair_key_fingerprint: "{{ _ssh_priv_key_result.fingerprint }}"