- name: Get the currently checked-out branch
  command:
    cmd: git rev-parse --abbrev-ref HEAD
    chdir: "{{ git_workspace_path }}"
  register: _git_checked_out_branch_result
  changed_when: false

- debug:
    var: _git_checked_out_branch_result