- name: Send SOAP request to revoke certificate by CEPO OrderID
  ansible.builtin.uri:
    url: "{{ globalsign_api_managed_ssl_service_url }}"
    method: POST
    headers:
      Content-Type: "text/xml; charset=utf-8"
    body: "{{ lookup('template', 'revoke_order_by_cepo.xml.j2') }}"
    return_content: true
    status_code: 200
  register: revoke_order_response