managed_ansible_vault_path: "{{ xdg_data_home_path }}/managed_ansible_vault"
managed_ansible_vault_password_file_path: "{{ managed_ansible_vault_path }}/ansible_vault_password_file"

managed_ansible_vault_user_secrets_path: "{{ (managed_ansible_vault_path, 'user_secrets') | path_join }}"
managed_ansible_vault_user_secret_path: "{{ (managed_ansible_vault_user_secrets_path, managed_ansible_vault_user_secret_name) | path_join }}"

_user_secret_var_name: "{{ managed_ansible_vault_user_secret_name }}"
_user_secret_var_value: "{{ vars[_user_secret_var_name] }}"