

_detected_managed_openssh_keypair_public_key_value: "{{ _ed25519_type_openssh_privatekey_file_result.public_key }}"
_detected_managed_openssh_keypair_key_fingerprint: "{{ _ed25519_type_openssh_privatekey_file_result.fingerprint }}"

managed_openssh_privatekey_with_passphrase_file_path: "{{ managed_openssh_keypair_directory_path }}/{{ managed_openssh_privatekey_with_passphrase_file_name }}"
managed_openssh_privatekey_with_passphrase_file_name: "{{ managed_openssh_privatekey_file_name }}_with_passphrase"

ed25519_type_openssh_privatekey_file_path: "{{ managed_openssh_keypair_directory_path }}/{{ managed_openssh_privatekey_without_passphrase_file_name }}"
managed_openssh_privatekey_without_passphrase_file_name: "{{ managed_openssh_privatekey_file_name }}_without_passphrase"

managed_openssh_privatekey_maybe_without_passphrase_file_path: "{{ managed_openssh_keypair_directory_path }}/{{ managed_openssh_privatekey_maybe_without_passphrase_file_name }}"
managed_openssh_privatekey_maybe_without_passphrase_file_name: "{{ managed_openssh_privatekey_file_name }}_maybe_without_passphrase"
