- blockinfile:
    path: "{{ xdg_user_home_ssh_directory_config_file_path }}"
    marker: "# {mark} Host catch-all always last - Ansible managed"
    create: true
    insertafter: EOF
    prepend_newline: true
    block: |
      Host *
        IdentitiesOnly yes
        IdentityFile ~/{{ xdg_user_home_ssh_priv_key_file_path_relative_to_xdg_user_home }}
