- file:
    state: directory
    path: "{{ managed_unarchive_path }}"

- import_tasks: get_checksum_and_archive_hash.yml

- include_tasks: idempotent_check_hash_unarchive.yml
  when: _managed_unarchive_hash_file_exists

- include_tasks: unarchive_and_hash.yml
  when: not _managed_unarchive_hash_file_exists
