- name: Add ~/{{ path_relative_to_user_home }} to PATH in profile file
  ansible.builtin.blockinfile:
    prepend_newline: true
    path: "{{ user_home_bashrc_file_path }}"
    block: |
      export PATH="$HOME/{{ path_relative_to_user_home }}:$PATH"
    marker: "# {mark} HOME/{{ path_relative_to_user_home }} - Ansible managed"
  notify: refresh user bash sessions using SIGHUP
  vars:
    path_relative_to_user_home: "{{ absolute_path_for_path_env_var | ansible.builtin.relpath(ansible_env.HOME) }}"
