- name: Set DNS server in systemd-resolved drop-in configuration
  community.general.ini_file:
    path: "{{ etc_systemd_resolved_conf_drop_in_file_path }}"
    section: Resolve
    option: DNS
    value: 192.168.1.1
    mode: '0644'
  become: true
  vars:
    systemd_resolved_conf_d_file_shortname: global_dns_localhost
  notify:
    - restart systemd-resolved and reload daemon