- import_tasks: priv_key_file_copied_with_nopass_suffix.yml

- name: Remove passphrase using ssh-keygen with -P and -N options
  ansible.builtin.command:
    cmd: ssh-keygen -p -P '{{ openssh_privatekey_file_passphrase }}' -N '' -f {{ managed_openssh_privatekey_without_passphrase_file_path }}
#  no_log: true

#- name: TEST AGAIN Remove passphrase using ssh-keygen with -P and -N options
#  ansible.builtin.command:
#    cmd: ssh-keygen -p -P '{{ openssh_privatekey_file_passphrase }}' -N '' -f {{ managed_openssh_privatekey_without_passphrase_file_path }}
#  no_log: true