- command:
    cmd: xrandr --listmonitors
  register: xrandr_listmonitors_result
  changed_when: false
  environment:
    DISPLAY: "{{ active_user_display_env_var_value }}"

- set_fact:
    xrandr_listed_monitors: "{{ _parsed_xrandr_listmonitors_result }}"
    cacheable: true
