- name: Register 1Password yum repo (which is used by dnf)
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    file: 1password
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    gpgcheck: yes
    enabled: yes
  become: yes