- name: Ensure jetbrains product settings directory exists
  file:
    path: "{{ jetbrains_product_config_dir_options_path }}"
    state: directory

- name: Create filetypes.xml if it doesn't exist
  copy:
    content: "<application></application>"
    dest: "{{ jetbrains_product_config_dir_options_filetypes_path }}"
    force: false

- name: Update jetbrains product settings filetype associations
  community.general.xml:
    path: "{{ jetbrains_product_config_dir_options_filetypes_path }}"
    xpath: "/application/component[@name='FileTypeManager']"
    state: present
    pretty_print: yes

- name: Ensure extensionMap exists inside FileTypeManager
  community.general.xml:
    path: "{{ jetbrains_product_config_dir_options_filetypes_path }}"
    xpath: "/application/component[@name='FileTypeManager']/extensionMap"
    state: present
    pretty_print: yes

- name: Ensure .gpg files are mapped to PLAIN_TEXT
  community.general.xml:
    path: "{{ jetbrains_product_config_dir_options_filetypes_path }}"
    xpath: "/application/component[@name='FileTypeManager']/extensionMap/mapping[@ext='gpg']"
    attribute: "type"
    value: "PLAIN_TEXT"
    state: present
    pretty_print: yes

- name: Ensure .crt files are mapped to PLAIN_TEXT
  community.general.xml:
    path: "{{ jetbrains_product_config_dir_options_filetypes_path }}"
    xpath: "/application/component[@name='FileTypeManager']/extensionMap/mapping[@ext='crt']"
    attribute: "type"
    value: "PLAIN_TEXT"
    state: present
    pretty_print: yes
