- name: Get merged branches via git for-each-ref
  command:
    cmd: git for-each-ref --merged HEAD --format="%(refname:short)" refs/heads/
    chdir: "{{ git_workspace_path }}"
  register: _git_for_each_ref_merged_branches_result
  changed_when: false


- debug:
    var: _git_workspace_fully_merged_branches_by_ref_except_active_branch_list