- name: git diff between local branch {{ git_workspace_branch_name }} and remote ({{ git_remote_name }}) branch {{ remote_git_branch_name }} versions
  command:
    cmd: git diff {{ git_workspace_branch_name }} {{ git_remote_name }}/{{ remote_git_branch_name }} --numstat
    chdir: "{{ git_workspace_path }}"
  register: _git_diff_local_to_remote_result
  failed_when: false
  changed_when: false

