- community.general.github_repo:
    access_token: "{{ github_personal_access_token }}"
    organization: "{{ github_organization | default(omit) }}"
    name: "{{ github_repo_name }}"
    description: "{{ github_repo_description | default(github_repo_name) }}"
    private: false
    force_defaults: false
    api_url: "{{ github_api_url | default(omit) }}"