- import_role:
    name: kcerts.x509.file_info
  vars:
    x509_cert_crt_file_path: "{{ managed_cert_crt_file_path }}"

- slurp:
    path: "{{ managed_cert_crt_file_path }}"
  register: _managed_cert_crt_file_slurp_result

- template:
    src: combined_cert_and_ca_intermediate.j2
    dest: "{{ managed_combined_cert_crt_and_ca_intermediate_file_path }}"
    mode: '0600'
  vars:
    certificate_content: "{{ _managed_cert_crt_file_slurp_result['content'] | b64decode }}"
