- name: Set permissions on /etc/passwd (this matches ansible-builder's implementation, but I am not 100% sure why it's needed)
  file:
    path: /etc/passwd
    mode: ug+rw

- name: Ensure that the /runner directory exists as a workdir for ansible-runner
  file:
    path: /runner
    state: directory
    group: 0
    mode: ug+rwx