- import_role:
    name: kgit_workspace.local_branch_info.list_branches

- debug:
    var: _git_workspace_branch_name_in_detected_branch_names_bool

- include_role:
    name: defaults
    tasks_from: new_branch_from_local_branch_head.yml
  vars:
    git_workspace_desired_branch_name: "{{ git_workspace_branch_name }}"
  when: not _git_workspace_branch_name_in_detected_branch_names_bool