# https://specifications.freedesktop.org/basedir-spec/latest/
xdg_user_home_path: "{{ ansible_env.HOME }}"
xdg_data_home_path: "{{ xdg_user_home_path }}/.local/share"
xdg_cache_home_path: "{{ xdg_user_home_path }}/.cache"
xdg_bin_home_path: "{{ xdg_user_home_path }}/.local/bin"
xdg_bin_home_file_path: "{{ xdg_bin_home_path }}/{{ xdg_bin_home_filename }}"
xdg_state_home_path: "{{ xdg_user_home_path }}/.local/state"
xdg_config_home_path: "{{ xdg_user_home_path }}/.config"
xdg_runtime_dir_path: /run/user/{{ ansible_user_uid }}
xdg_desktop_dir_path: "{{ xdg_user_home_path }}/Desktop"
xdg_desktop_dir_file_path: "{{ xdg_desktop_dir_path }}/{{ xdg_desktop_dir_filename }}"
xdg_download_dir_path: "{{ xdg_user_home_path }}/Downloads"
xdg_download_dir_file_path: "{{ xdg_download_dir_path }}/{{ xdg_download_dir_filename }}"
xdg_data_home_applications_path: "{{ xdg_data_home_path }}/applications"