- include_role:
    name: "{{ target_role_fqrn }}"
  loop:
  - kpacman.state.cache_check
  - kpacman.state.clean_cache
  - kpacman.keyring.refresh_keys
  - kpacman.keyring.key_init
  - kpacman.keyring.populate_archlinux_keys
  - kpacman.state.paccheck
  loop_control:
    loop_var: target_role_fqrn
