dependencies:
- name: korbad.dnf.package_installed
  dnf_package_name: rustup
  when: ansible_distribution == 'Fedora'
- name: korbad.dnf.package_installed
  dnf_package_name: '@development-tools'
  when: ansible_distribution == 'Fedora'