- import_role:
    name: mfilesystem.directory.exists
  vars:
    managed_directory_path: "{{ xdg_bin_home_path }}"

- import_role:
    name: kfreedesktop.bin.symlink
  vars:
    symlink_src_path: "{{ managed_unarchive_path }}/{{ rustrover_directory_name }}/bin/rustrover"
    xdg_bin_home_filename: rustrover
    rustrover_directory_name: RustRover-2024.3.4
