- name: Create random vault password file
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits,punctuation') }}"
    dest: "{{ vault_password_file_path }}"
    mode: u+rw,og-rwx
  no_log: true