- stat:
    path: "{{ vault_password_file_path }}"
  register: _vault_password_file_stat_result

- include_tasks: generate_password_file.yml
  when: not _vault_password_file_stat_result.stat.exists

- name: Ensure file has the correct permissions
  ansible.builtin.file:
    path: "{{ vault_password_file_path }}"
    state: file
    mode: u=rw,g-rwx,o-rwx