- command:
    cmd: git ls-remote --quiet --branches {{ git_remote_name }}
    chdir: "{{ git_workspace_path }}"
  changed_when: false
  register: _git_workspace_git_ls_remote_branches_for_remote_result

- debug:
    var: _git_workspace_git_ls_remote_branches_for_remote