- name: Send SOAP request for GetCertByCSR
  ansible.builtin.uri:
    url: "{{ globalsign_api_managed_ssl_service_url }}"
    method: POST
    headers:
      Content-Type: "text/xml; charset=utf-8"
    body: "{{ lookup('template', 'get_cert_by_csr.xml.j2') }}"
    return_content: true
    status_code: 200
  register: globalsign_get_cert_response
