- import_role:
    name: kgit_workspace.local_branch_info.list_branches

- import_role:
    name: kgit_workspace.active_worktree_info.git_worktree_active_branch_name

- include_tasks: soft_git_branch_delete.yml
  when:
  - _git_workspace_branch_name_in_detected_branch_names_bool
  - not _git_workspace_branch_name_equalto_worktree_active_branch_name