- name: Ensure umask 077 block exists in .bashrc
  ansible.builtin.blockinfile:
    path: "{{ xdg_user_home_bashrc_file_path }}"
    block: |
      umask 077
    marker: "# {mark} UMASK BLOCK - Ansible managed"
  notify: refresh user bash sessions using SIGHUP