- import_role:
    name: kopenssh_keypair.privatekey.info
  vars:
    openssh_privatekey_file_path: "{{ managed_openssh_privatekey_maybe_without_passphrase_file_path }}"

- copy:
    src: "{{ managed_openssh_privatekey_maybe_without_passphrase_file_path }}"
    dest: "{{ managed_openssh_privatekey_without_passphrase_file_path }}"
    remote_src: true
    force: true
    mode: 'o-rxw,g-rxw'
  when: not _detected_openssh_privatekey_file_passphrase_protection

- import_role:
    name: kopenssh_keypair.privatekey.info
  vars:
    openssh_privatekey_file_path: "{{ managed_openssh_privatekey_without_passphrase_file_path }}"

- assert:
    that:
    - not _detected_openssh_privatekey_file_passphrase_protection
