- name: Disable mDNS in systemd-resolved drop-in configuration (note that systemd-resolved doesn't support service discovery (such as hostname.local))
  community.general.ini_file:
    path: "{{ etc_systemd_resolved_conf_drop_in_file_path }}"
    section: Resolve
    option: MulticastDNS
    value: no
    mode: '0644'
  become: true
  vars:
    systemd_resolved_conf_d_file_shortname: mdns
  notify:
    - restart systemd-resolved and reload daemon