- name: Ensure ansible-vault artifact directory exists with proper permissions
  ansible.builtin.file:
    state: directory
    path: "{{ managed_ansible_vault_path }}"
    mode: 'u=rwx,g-rw,o-rw'

- import_role:
    name: kansible.vault_config.password_file_exists
  vars:
    vault_password_file_path: "{{ managed_ansible_vault_password_file_path }}"