- import_role:
    name: kfreedesktop.dconf.value_set
  vars:
    gsettings_schema: org.gnome.desktop.default-applications.terminal
    gsettings_key: exec
    gsettings_value: "{{ nemo_default_terminal_exec }}"

- import_role:
    name: kfreedesktop.dconf.value_set
  vars:
    gsettings_schema: org.gnome.desktop.default-applications.terminal
    gsettings_key: exec-arg
    gsettings_value: "{{ nemo_default_terminal_exec_argument }}"