
- name: git workspace {{ git_workspace_path }} force add submodule {{ git_workspace_submodule_relative_path }} from {{ git_repo_remote_full_url }}
  command:
    cmd: git submodule add -b {{ git_workspace_submodule_branch_name }} --force {{ git_repo_remote_full_url }} {{ git_workspace_submodule_relative_path }}
    chdir: "{{ git_workspace_path }}"
