---
- name: Ensure jetbrains product settings directory exists
  file:
    path: "{{ jetbrains_product_config_dir_options_path }}"
    state: directory

- name: Create project.default.xml if it doesn't exist
  copy:
    content: "<application></application>"
    dest: "{{ jetbrains_product_config_dir_options_project_default_path }}"
    force: false

- name: Update jetbrains product settings to exclude git-ignored files from indexing
  community.general.xml:
    path: "{{ jetbrains_product_config_dir_options_project_default_path }}"
    xpath: "/application/component[@name='ProjectView']/panes/pane[@id='ProjectPane']/option[@name='showExcludedFiles']"
    attribute: "value"
    value: "false"
    pretty_print: yes

- name: Ensure git-ignored files are excluded from search
  community.general.xml:
    path: "{{ jetbrains_product_config_dir_options_project_default_path }}"
    xpath: "/application/component[@name='ProjectView']/panes/pane[@id='ProjectPane']/option[@name='hideIgnored']"
    attribute: "value"
    value: "true"
    pretty_print: yes
