---
- import_role:
    name: kfilesystem.state.ensure_filesystem_write_buffering_is_complete

- name: Gather facts
  setup:
    filter: ansible_devices,ansible_mounts

- name: Create device dictionary
  set_fact:
    device_dict: "{{ nonunique_device_dict | dict2items | rejectattr('key', 'search', 'wwn-') | items2dict }}"
    cacheable: true
  vars:
    nonunique_device_dict: "{{ lookup('template', 'device_dict.j2') | from_yaml }}"
