- community.crypto.get_certificate:
    host: "{{ get_cert_remote_host_fqdn }}"
    port: "{{ get_cert_remote_host_port }}"
    get_certificate_chain: true
    ca_cert: "{{ root_certs_pem_file_path }}"