- import_role:
    name: kgit.workspace_info.status

- import_role:
    name: kgit.workspace_info.stash_list

- include_tasks: check_branches.yml
  when:
  - not _git_stash_detected_bool
  - not _git_status_untracked_files_detected
  - not _git_status_unstaged_changes_detected
  - not _git_status_uncommited_changes_detected