- name: Check file type
  ansible.builtin.command:
    cmd: "file {{ keyfile_path }}"
  register: file_type
  changed_when: false

- name: Get SSH key fingerprint
  ansible.builtin.command:
    cmd: "ssh-keygen -l -f {{ keyfile_path }}"
  register: ssh_fingerprint
  failed_when: false
  changed_when: false

- name: Try extracting public key
  ansible.builtin.command:
    cmd: "ssh-keygen -y -f {{ keyfile_path }}"
  register: ssh_pubkey
  failed_when: false
  changed_when: false

- name: Check OpenSSL RSA format
  ansible.builtin.command:
    cmd: "openssl rsa -in {{ keyfile_path }} -noout -text"
  register: rsa_check
  failed_when: false
  changed_when: false

- name: Check OpenSSL EC format
  ansible.builtin.command:
    cmd: "openssl ec -in {{ keyfile_path }} -noout -text"
  register: ec_check
  failed_when: false
  changed_when: false

- name: Check OpenSSL DSA format
  ansible.builtin.command:
    cmd: "openssl dsa -in {{ keyfile_path }} -noout -text"
  register: dsa_check
  failed_when: false
  changed_when: false

- name: Check OpenSSL Ed25519 format
  ansible.builtin.command:
    cmd: "openssl pkey -in {{ keyfile_path }} -noout -text"
  register: ed25519_check
  failed_when: false
  changed_when: false

- name: Debug key information
  ansible.builtin.debug:
    msg:
    - "File Type: {{ file_type.stdout }}"
    - "SSH Fingerprint: {{ ssh_fingerprint.stdout | default('Unknown') }}"
    - "Public Key Extraction: {{ ssh_pubkey.stdout | default('Failed or Encrypted') }}"
    - "RSA Check: {{ rsa_check.stdout | default('Not RSA or Encrypted') }}"
    - "EC Check: {{ ec_check.stdout | default('Not EC or Encrypted') }}"
    - "DSA Check: {{ dsa_check.stdout | default('Not DSA or Encrypted') }}"
    - "Ed25519 Check: {{ ed25519_check.stdout | default('Not Ed25519 or Encrypted') }}"
