- name: Deploy ssh-agent service unit
  template:
    src: ssh-agent.service.j2
    dest: "{{ systemd_user_unit_file_path }}"
    mode: '0644'
  notify:
    - reload systemd user daemon

- meta: flush_handlers

- import_role:
    name: jsystemd.user_unit.ensure_enabled

- import_role:
    name: jsystemd.user_unit.started
