_globalsign_cert_by_orderid_response_xml_content: "{{ _globalsign_cert_by_orderid_response.content }}"
_globalsign_cert_by_orderid_response_dict_content: "{{ _globalsign_cert_by_orderid_response_xml_content | ansible.utils.from_xml }}"
