- find:
    paths: "{{ nemo_actions_directory_path }}"
    file_type: file
    patterns: "*.nemo_action"
  register: _found_nemo_actions_result

- file:
    state: absent
    path: "{{ __some_file_path }}"
  loop: "{{ _found_nemo_action_file_paths }}"
  loop_control:
    loop_var: __some_file_path
  vars:
    _found_nemo_action_files: "{{ _found_nemo_actions_result.files }}"
    _found_nemo_action_file_paths: "{{ _found_nemo_action_files | map(attribute='path') }}"

