- name: Configure Certificate Signing Request (CSR) file
  community.crypto.openssl_csr:
    path: "{{ openssl_csr_file_path }}"
    privatekey_path: "{{ openssl_privatekey_file_path }}"
    common_name: "{{ openssl_csr_common_name }}"
    country_name: "{{ openssl_csr_country_name | default(omit) }}"
    organizational_unit_name: "{{ openssl_csr_organizational_unit_name | default(omit) }}"
    state_or_province_name: "{{ openssl_csr_state_or_province_name | default(omit)  }}"
    locality_name: "{{ openssl_csr_locality_name | default(omit)  }}"
    organization_name: "{{ openssl_csr_organization_name | default(omit)  }}"
    subject_alt_name: "{{ openssl_csr_subject_alt_name | default(omit) }}"
