- name: Generate Certificate Signing Request (CSR)
  community.crypto.openssl_csr:
    path: "{{ ssl_csr_file_path }}"
    privatekey_path: "{{ ssl_privatekey_file_path }}"
    common_name: "{{ ssl_csr_common_name }}"