- name: Send SOAP request for {{ globalsign_api_domain_name }}
  ansible.builtin.uri:
    url: "{{ globalsign_api_managed_ssl_service_url }}"
    method: POST
    headers:
      Content-Type: "text/xml; charset=utf-8"
    body: "{{ lookup('template', 'get_domains.xml.j2') }}"
    return_content: true
    status_code: 200
  register: _globalsign_api_domain_response

- debug:
    var: _globalsign_api_domain_response_dict_content