- name: Send SOAP request to get certificate for GlobalSign OrderID {{ globalsign_order_id }}
  ansible.builtin.uri:
    url: "{{ globalsign_api_gas_service_url }}"
    method: POST
    headers:
      Content-Type: "text/xml; charset=utf-8"
    body: "{{ lookup('template', 'get_cert_by_cepo.xml.j2') }}"
    return_content: true
    status_code: 200
  register: _globalsign_cert_by_orderid_response

- debug:
    var: _globalsign_cert_by_orderid_response_dict_content