- assert:
    that:
    - yaml_file_path is defined

- file:
    state: directory
    path: "{{ yaml_file_path | dirname }}"

- template:
    src: yaml_file.yml.j2
    dest: "{{ yaml_file_path }}"
    force: true
  register: _yaml_file_result