- blockinfile:
    path: "{{ xdg_user_home_ssh_directory_config_file_path }}"
    marker: "# {mark} Host {{ ssh_config_host_fqdn }} entry - Ansible managed"
    insertbefore: "^# BEGIN Host catch-all always last - Ansible managed"
    block: |
      Host {{ ssh_config_host_fqdn }}
        AddKeysToAgent yes
        IdentityFile ~/{{ xdg_user_home_ssh_priv_key_file_path_relative_to_xdg_user_home }}
