- name: Get i3 socket path
  shell: i3 --get-socketpath
  register: i3_socket_path_result
  environment:
    DISPLAY: "{{ active_user_display_env_var_value }}"
  changed_when: false

- name: Set fact for i3 socket path
  set_fact:
    i3_socket_path: "{{ i3_socket_path_result.stdout }}"
    cacheable: true