- name: Perform collection installation via ansible-galaxy
  community.general.ansible_galaxy_install:
    type: collection
    name: "{{ collection_namespace_dot_collection_name }}"
    dest: "{{ collections_path }}"
