dependencies:
  - name: kpython.managed_virtual_environment.configured
    virtual_environment_base_interpreter_path: /usr/bin/python3.13
    managed_virtual_environment_name: default
    virtual_environment_packages:
      - ansible-core>=2.16,<2.17
      - podman
      - lxml
      - requests-oauthlib
      - jmespath
      - pexpect
      - psutil
      - PyGithub
      - xmltodict
      - ansible-navigator
