- assert:
    that:
    - yaml_file_with_vault_encrypted_data_path is defined
    - variable_value_to_vault_encrypt is defined
    - vault_password is defined

- file:
    state: directory
    path: "{{ yaml_file_with_vault_encrypted_data_path | dirname }}"

- template:
    src: yaml_file.yml.j2
    dest: "{{ yaml_file_with_vault_encrypted_data_path }}"
  vars:
    variable_encrypted_value_in_yaml_file: "{{ variable_value_to_vault_encrypt|vault(vault_password) }}"
  no_log: true
