#- command:
#    cmd: pacman -Syu
#  become: true

- community.general.pacman:
    upgrade: true
    update_cache: true
  become: true
  register: _pacman_upgrade_result
  changed_when: _pacman_upgrade_result.packages | length > 0
