- import_role:
      name: kgit_workspace.config.key_set
  vars:
      git_workspace_config_key_name: "{{ git_workspace_config_remote_pushurl_key_name }}"
      git_workspace_config_key_value: "{{ git_repo_remote_full_url }}"