- name: Gather Certificate Signing Request (CSR) file info
  community.crypto.openssl_csr_info:
    path: "{{ ssl_csr_file_path }}"
  register: _ssl_csr_file_info_result

- debug:
    var: _ssl_csr_file_info_result