- name: Gather Certificate Signing Request (CSR) file info
  community.crypto.openssl_csr_info:
    path: "{{ openssl_csr_file_path }}"
  register: _openssl_csr_file_info_result

- debug:
    var: _openssl_csr_file_info_result