_globalsign_api_domain_response_xml_content: "{{ _globalsign_api_domain_response.content }}"
_globalsign_api_domain_response_dict_content: "{{ _globalsign_api_domain_response_xml_content | ansible.utils.from_xml }}"
