- name: Open SSH keypair, never regenerated, no passphrase, at {{ openssh_privatekey_file_path }}
  community.crypto.openssh_keypair:
    path: "{{ openssh_privatekey_file_path }}"
    regenerate: never
    type: rsa
  register: _openssh_privatekey_file_without_passphrase_result