mount_points_by_disk_id: "{{ device_dict[disk_id].partitions.values() | map(attribute='mounts') | list | flatten }}"
mount_points_by_partition: "{{ device_dict[disk_id].partitions[partition_number | string].mounts }}"
unmounted_partitions_by_disk_id: "{{ device_dict[disk_id].partitions | dict2items | selectattr('value.mounts', 'equalto', []) | map(attribute='key') | list }}"
disk_ids: "{{ device_dict.keys() | list }}"
is_partition_mounted: "{{ mount_points_by_partition | count | int > 0 }}"
is_partition_mounted_at_path: "{{ mount_point_path in mount_points_by_partition }}"
disk_id_partitions: "{{ device_dict[disk_id].partitions | list }}"
does_partition_exist_by_disk_id: "{{ partition_number|string in disk_id_partitions }}"
is_partition_mounted_at_fs_root: "{{ '/' in mount_points_by_partition }}"
is_partition_mounted_at_efi: "{{ '/efi' in mount_points_by_partition }}"
disk_id_contains_root_fs_mount_point: "{{ '/' in mount_points_by_disk_id }}"
disk_id_contains_efi_mount_point: "{{ '/efi' in mount_points_by_disk_id }}"
disk_id_has_mount_points: "{{ mount_points_by_disk_id | count | int > 0 }}"
_disks: "{{ device_dict | dict2items }}"
_disk_id_with_root_fs: "{{ _disks | json_query(\"[?contains(value.partitions.*.mounts[], '/')].key\") | first }}"
_partition_number_with_root_fs: "{{ _disks | selectattr('key', 'eq', _disk_id_with_root_fs) | map(attribute='value') | map(attribute='partitions') | first | dict2items | selectattr('value.mounts', 'contains', '/') | map(attribute='key') | first }}"
_partition_number_with_esp: "{{ _disks | selectattr('key', 'eq', _disk_id_with_root_fs) | map(attribute='value') | map(attribute='partitions') | first | dict2items | selectattr('value.mounts', 'contains', '/efi') | map(attribute='key') | first }}"
