- name: Ensure that the keymaps directory exists
  file:
    path: "{{ jetbrains_product_config_dir_keymaps_path }}"
    state: directory

- copy:
    content: <keymap version="1" name="{{ keymap_file_shortname }}"/>
    dest: "{{ jetbrains_product_config_dir_keymap_file_path }}"
    force: false

- import_tasks: process_keymap_file.yml