- name: Ensure {{ container_name }} from {{ container_image_fully_qualified_name }} is running, detached, interactive - with tmp volume mount
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "{{ container_image_fully_qualified_name }}"
    image_strict: true
    state: started
    detach: true
    interactive: true
    volumes:
    - "{{ container_host_tmp_volume_mount_path }}:/tmp:Z"