- community.crypto.openssl_privatekey:
    path: "{{ ssl_privatekey_file_path }}"
    size: 4096
    type: RSA
    return_content: true
    regenerate: never
  register: _ssl_privatekey_file_result
  no_log: true
