- name: Ensure jetbrains product settings directory exists
  file:
    path: "{{ jetbrains_product_config_dir_options_path }}"
    state: directory

- name: Create indexing.xml if it doesn't exist
  copy:
    content: "<application-level-options></application-level-options>"
    dest: "{{ jetbrains_product_config_dir_options_indexing_path }}"
    force: false

- name: Disable file-based indexing settings
  community.general.xml:
    path: "{{ jetbrains_product_config_dir_options_indexing_path }}"
    xpath: "/application-level-options/component[@name='FileBasedIndex']/option[@name='indexExcludedFiles']"
    attribute: "value"
    value: "false"
    pretty_print: yes