- file:
    path: "{{ desktop_entry_file_path | dirname }}"
    state: directory

- template:
    src: desktop_entry.j2
    dest: "{{ desktop_entry_file_path }}"
    mode: '0744'
  notify:
  - update desktop database

- import_role:
    name: validate