---
- name: For each ref, get local (head) branches
  command:
    cmd: git for-each-ref --format='%(refname:short)' refs/heads/
    chdir: "{{ git_workspace_path }}"
  register: _git_for_each_ref_head_refs_result
  changed_when: false