- name: Ensure git workspace {{ git_workspace_path }} config key {{ git_workspace_config_key_name }} has value {{ git_workspace_config_key_value }}
  community.general.git_config:
    repo: "{{ git_workspace_path }}"
    scope: local
    name: "{{ git_workspace_config_key_name }}"
    value: "{{ git_workspace_config_key_value }}"